In [2]:
import torch

In [3]:
torch.rand(3, 4)

tensor([[0.1462, 0.3267, 0.1928, 0.3255],
        [0.9916, 0.6592, 0.8273, 0.7499],
        [0.6786, 0.7380, 0.4397, 0.4497]])

In [4]:
torch.rand(3, 4, 5)

tensor([[[0.3973, 0.6106, 0.2144, 0.6260, 0.7817],
         [0.0878, 0.0460, 0.0059, 0.0225, 0.3411],
         [0.7681, 0.0165, 0.0093, 0.3702, 0.7436],
         [0.5012, 0.3487, 0.1364, 0.5492, 0.5126]],

        [[0.5078, 0.7610, 0.7567, 0.6432, 0.0872],
         [0.6493, 0.2475, 0.2856, 0.9971, 0.4556],
         [0.1215, 0.1828, 0.0997, 0.9349, 0.6707],
         [0.3137, 0.7288, 0.8210, 0.4418, 0.1624]],

        [[0.2355, 0.5048, 0.1761, 0.7707, 0.9159],
         [0.6375, 0.0389, 0.7567, 0.9958, 0.2644],
         [0.0545, 0.6112, 0.8328, 0.9353, 0.1781],
         [0.9091, 0.7099, 0.2386, 0.9250, 0.9840]]])

In [5]:
torch.rand(3, 224, 224)

tensor([[[0.9142, 0.0070, 0.9393,  ..., 0.6539, 0.6822, 0.8317],
         [0.5928, 0.0778, 0.9418,  ..., 0.2929, 0.2387, 0.0858],
         [0.8179, 0.8754, 0.1577,  ..., 0.8199, 0.7577, 0.7130],
         ...,
         [0.0894, 0.2496, 0.5179,  ..., 0.1612, 0.5464, 0.8591],
         [0.2010, 0.2324, 0.8266,  ..., 0.3239, 0.8193, 0.5794],
         [0.8010, 0.1906, 0.0511,  ..., 0.0978, 0.5858, 0.5906]],

        [[0.1116, 0.3052, 0.2720,  ..., 0.9012, 0.2381, 0.2677],
         [0.2649, 0.7937, 0.2846,  ..., 0.4867, 0.6284, 0.5542],
         [0.6595, 0.9590, 0.3907,  ..., 0.3235, 0.9586, 0.2340],
         ...,
         [0.8296, 0.5829, 0.9840,  ..., 0.6825, 0.9349, 0.7898],
         [0.7462, 0.3247, 0.6430,  ..., 0.9396, 0.6552, 0.3841],
         [0.7919, 0.4024, 0.9307,  ..., 0.8950, 0.5931, 0.9517]],

        [[0.2861, 0.8903, 0.3293,  ..., 0.5745, 0.6256, 0.5297],
         [0.4538, 0.4075, 0.7280,  ..., 0.9491, 0.4233, 0.9324],
         [0.6194, 0.7096, 0.1774,  ..., 0.7268, 0.3776, 0.

Tensor of Zeros and Ones

In [7]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

range of tensors

In [9]:
torch.range(0, 10)

C:\Users\Senthil\AppData\Local\Temp\ipykernel_25272\1549641488.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Tensors like

In [14]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

tensor datatypes

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False) # default dtype is float32

In [16]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [18]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [19]:
int_32_tensor = float_32_tensor.type(torch.int32)

In [21]:
float_16_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [23]:
some_tensor = torch.rand(3, 4)

In [24]:
some_tensor

tensor([[0.7592, 0.7440, 0.3213, 0.0402],
        [0.4830, 0.3745, 0.7837, 0.7572],
        [0.0150, 0.4205, 0.2302, 0.5573]])

In [25]:
print("Datatype of tensor: ", some_tensor.dtype)
print("Shape of tensor: ", some_tensor.shape)
print("Device in which the tensor is on: ", some_tensor.device)

Datatype of tensor:  torch.float32
Shape of tensor:  torch.Size([3, 4])
Device in which the tensor is on:  cpu


Matrix Manipulation

1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Matrix Multiplication

In [26]:
tensor = torch.tensor([1, 2, 3])

In [27]:
tensor + 10

tensor([11, 12, 13])

In [29]:
torch.add(tensor, 1)

tensor([2, 3, 4])

In [30]:
tensor - 10

tensor([-9, -8, -7])

In [31]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

In [32]:
tensor * 10

tensor([10, 20, 30])

In [33]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [34]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [35]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

In [36]:
torch.matmul(tensor, tensor)

tensor(14)

In [42]:
value = 0
%%time
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

print(value)

UsageError: Line magic function `%%time` not found.
