#### Training Nural Network with Pytorch

##### A deeper dive into loading data

In [1]:
import torch
import torch.nn as nn
import pandas as pd

In [2]:
animals = pd.read_csv("./datasets/animals_dataset.csv")

In [3]:
# 0. bird
# 1. mammal
# 2. reptile

In [4]:
features = animals.iloc[:, 1:-1]  # leaving out the name and target column
X = features.to_numpy()
y = animals.iloc[:, -1]

In [6]:
from torch.utils.data import TensorDataset

dataset = TensorDataset(torch.tensor(X), torch.tensor(y))

input_sample, output_label = dataset[0]

print("Input Sample: ", input_sample)
print("Output Sample: ", output_label)

Input Sample:  tensor([0, 1, 1, 0, 0, 2, 1])
Output Sample:  tensor(0)


Data Loader

In [7]:
from torch.utils.data import DataLoader

batch_size = 2
shuffle = True

dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)

In [9]:
for batch_input, batch_label in dataloader:
    print("Batch Input: \n", batch_input)
    print("Batch Label: \n", batch_label)

Batch Input: 
 tensor([[0, 0, 1, 0, 1, 4, 1],
        [1, 0, 0, 1, 0, 4, 1]])
Batch Label: 
 tensor([2, 1])
Batch Input: 
 tensor([[0, 1, 1, 0, 0, 2, 1],
        [0, 1, 1, 0, 1, 2, 1]])
Batch Label: 
 tensor([0, 0])
Batch Input: 
 tensor([[1, 0, 0, 1, 1, 4, 1]])
Batch Label: 
 tensor([1])
