#### Neural Network Architecture and Hyperparameters

##### Discovering activation Functions

In [1]:
import torch 
import torch.nn as nn

The sigmoid and softmax ffunctions

In [3]:
input_tensor = torch.tensor([[2.4]])
sigmoid = nn.Sigmoid()
probability = sigmoid(input_tensor)
print(probability)

tensor([[0.9168]])


In [4]:
import numpy as np
1 / (1 + np.exp(-1 * 2.4))

np.float64(0.9168273035060777)

In [5]:
input_tensor = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])
softmax = nn.Softmax()
probabilities = softmax(input_tensor)
print(probabilities)

tensor([[1.2828e-01, 1.1698e-04, 5.7492e-01, 3.4961e-02, 1.5669e-01, 1.0503e-01]])


c:\Users\Senthil\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\nn\modules\module.py:1783: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


##### Running a Forward pass

Building a Binary Classifier in Pytorch

In [7]:
# predicting weather an animal is a mamal or not

# 5 animals, 6 features

input_tensor = torch.tensor(
    [
        [-0.4421, 1.5207, 2.0607, -0.3647, 0.4691, 0.0946],
        [-0.9155, -0.0475, -1.3645, 0.6336, -1.9520, -0.3398],
        [0.7406, 1.6763, -0.8511, 0.2432, 0.1123, -0.0633],
        [-1.6630, -0.0718, -0.1285, 0.5396, -0.0288, -0.8622],
        [-0.7413, 1.7920, -0.0883, -0.6685, 0.4745, -0.4245]
    ]
)

In [16]:
model = nn.Sequential(
    nn.Linear(6, 4),
    nn.Linear(4, 1),
    nn.Sigmoid()
)

In [17]:
probabilities = model(input_tensor)
print(probabilities)

tensor([[0.5543],
        [0.5620],
        [0.4825],
        [0.5426],
        [0.5341]], grad_fn=<SigmoidBackward0>)


In [18]:
predictions = ["yes" if probability > 0.5 else "no" for probability in probabilities]
print(predictions)

['yes', 'yes', 'no', 'yes', 'yes']


Building a Softmax classifier in Pytorch

In [19]:
# predict if an animal is 1.mammal, 2.bird, 3.reptile
n_classes = 3
input_tensor = torch.tensor(
    [
        [-0.4421, 1.5207, 2.0607, -0.3647, 0.4691, 0.0946],
        [-0.9155, -0.0475, -1.3645, 0.6336, -1.9520, -0.3398],
        [0.7406, 1.6763, -0.8511, 0.2432, 0.1123, -0.0633],
        [-1.6630, -0.0718, -0.1285, 0.5396, -0.0288, -0.8622],
        [-0.7413, 1.7920, -0.0883, -0.6685, 0.4745, -0.4245]
    ]
)

In [35]:
model = nn.Sequential(
    nn.Linear(6, 4),
    nn.Linear(4, n_classes),
    nn.Softmax(dim=-1)
)

proabilities = model(input_tensor)
predictions = torch.argmax(probabilities, dim=1)
print(predictions)

tensor([0, 0, 0, 0, 0])


##### Using loss functions to assess model predictions 

Transforming Labels with One Hot Encoding

In [36]:
import torch.nn.functional as F 

In [37]:
print(F.one_hot(torch.tensor(0), num_classes=3))

tensor([1, 0, 0])


In [38]:
print(F.one_hot(torch.tensor(1), num_classes=3))

tensor([0, 1, 0])


In [39]:
print(F.one_hot(torch.tensor(2), num_classes=3))

tensor([0, 0, 1])


Cross Entropy Loss

In [40]:
from torch.nn import CrossEntropyLoss

scores = torch.tensor([[-5.2, 4.6, 0.8]])
one_hot_target = torch.tensor([[1, 0, 0]])

criterion = CrossEntropyLoss()
print(criterion(scores.double(), one_hot_target.double()))

tensor(9.8222, dtype=torch.float64)


Creating one hot encoded labels using numpy and pytorch

In [41]:
import numpy as np 
import torch.nn.functional as F

In [42]:
one_hot_numpy = np.array([0, 1, 0])
one_hot_pytorch = F.one_hot(torch.tensor(1), num_classes=3)

print(one_hot_numpy)
print(one_hot_pytorch)

[0 1 0]
tensor([0, 1, 0])


Calculating cross entropy scores

In [44]:
y = [2]
scores = torch.tensor([[0.1, 6.0, -2.0, 3.2]])
target = F.one_hot(torch.tensor(y), num_classes=4)

criterion = CrossEntropyLoss()
loss = criterion(scores.double(), target.double())
print(loss)

tensor(8.0619, dtype=torch.float64)
