#### Introduction to PyTorch, a Deep Learning Library

In [1]:
import torch

Introduction to DeepLearning with Pytorch

In [2]:
temperatures = [[72, 75, 78], [70, 73, 76]]
temp_tensor = torch.tensor(temperatures)
print(temp_tensor)

tensor([[72, 75, 78],
        [70, 73, 76]])


Checking and Adding Tensors

In [4]:
adjustment = torch.tensor([[2, 2, 2], [2, 2, 2]])
adj_tensor = torch.tensor(adjustment)
print(adj_tensor)

tensor([[2, 2, 2],
        [2, 2, 2]])


C:\Users\Senthil\AppData\Local\Temp\ipykernel_23304\194978568.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  adj_tensor = torch.tensor(adjustment)


In [6]:
print(temp_tensor.shape)
print(temp_tensor.dtype)

torch.Size([2, 3])
torch.int64


In [8]:
print(adj_tensor.shape)
print(adj_tensor.dtype)

torch.Size([2, 3])
torch.int64


In [9]:
crted_tensor = temp_tensor + adj_tensor

In [10]:
crted_tensor

tensor([[74, 77, 80],
        [72, 75, 78]])

Multiplying Tensors

In [11]:
temp_tensor * adj_tensor

tensor([[144, 150, 156],
        [140, 146, 152]])

Matrix Multiplication

In [14]:
a = torch.tensor([[1, 2, 3], 
                  [1, 2, 3]])

b = torch.tensor([[1, 2], 
                  [3, 4],
                  [5, 6]])

print(a@b)

tensor([[22, 28],
        [22, 28]])


##### Nural Networks and Layers

Linear layer network


In [15]:
import torch
import torch.nn as nn 

input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])

linear_layer = nn.Linear(in_features=3, out_features=2)

output_tensor = linear_layer(input_tensor)

print(output_tensor)

tensor([[ 0.1155, -0.1014]], grad_fn=<AddmmBackward0>)


Print Weight and Bias

In [16]:
linear_layer.weight

Parameter containing:
tensor([[ 0.0668, -0.1764, -0.4907],
        [ 0.3861,  0.2181,  0.3367]], requires_grad=True)

In [17]:
linear_layer.bias

Parameter containing:
tensor([ 0.0569, -0.2553], requires_grad=True)

##### Hidden Layers and Parameters

My first Nural Network

In [26]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])
model = nn.Sequential(
    nn.Linear(in_features=8, out_features=4),
    nn.Linear(in_features=4, out_features=1)
)

output_tensor = model(input_tensor)

print(output_tensor)

tensor([[0.0848]], grad_fn=<AddmmBackward0>)


Counting the number of parameters

In [ ]:
# 94 42 21

# [(9 * 4) + 4] + [(4 * 2) + 2] + [(2 * 1) + 1] = [36 + 4] + [8 + 2] + [2 + 1] = 40 + 10 + 3 = 53

model = nn.Sequential(
    nn.Linear(9, 4),
    nn.Linear(4, 2),
    nn.Linear(2, 1)
)

total = 0

for p in model.parameters():
    total += p.numel()

print("Total number of Parameters: ", total)

Total number of Parameters:  53
